### ISSUE TITLE
Gmail GUI updated quicklink is not working anymore

### ISSUE THREAD

**Issue by jad00gar** [kevinwucodes/gmail-quick-links#52] opened 2020-10-22 23:24 UTC
Hello,
Gmail gui upgraded today and quick link is no longer working for me.
can you please advise if there is anything I can do to fix it.

thanks

**Comment by jad00gar** [comment] 2020-10-22 23:30
Actually it's working intermittingly.

**Comment by alexspeller** [comment] 2020-10-25 18:16
Logging out and logging in again fixed it for me with the new design.

Duplicate of #51

**Comment by kevinwucodes** [comment] 2020-10-30 03:45
I'm unable to reproduce this error.  Closing this issue for now.  Please open a new issue if this continues to occur.

**Closed by kevinwucodes** 2020-10-30 03:45 UTC
