### ISSUE TITLE
My Links DIsappeared

### ISSUE THREAD

**Issue by jeff9315** [kevinwucodes/gmail-quick-links#26] opened 2018-11-13 13:44 UTC
Today all my Quick Links disappeared. 

Here is a screenshot from the console showing an error message

![capture](https://user-images.githubusercontent.com/20246623/48417228-3fca6a80-e720-11e8-8be7-b1064f020939.PNG)

**Comment by BillGettys** [comment] 2018-11-13 13:50
My Quick Links also disappeared.  I noticed that Google installed a new version of Chrome this morning:

Google Chrome is up to date
Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by gwinston99** [comment] 2018-11-13 15:40
I'm having the exact same issue on Opera

Loaded Gmail Quick Links
chrome-extension://e…links.bundle.js:291 Uncaught TypeError: Cannot read property '1' of null
    at injectReact (chrome-extension://e…links.bundle.js:291)
    at chrome-extension://e…links.bundle.js:347

**Comment by jeff9315** [comment] 2018-11-13 20:23
Did everyone's issues start today? It looks like we have the same basic issue in Chrome, Firefox, and Opera.

**Comment by kevinwucodes** [comment] 2018-11-13 22:14
It looks like Gmail updated it's classes due to a new UI change.  I know what the issue is and I can have this fixed tonight and will push out a new release.

**Comment by kevinwucodes** [comment] 2018-11-14 01:17
Fixed in v0.3.7

**Closed by kevinwucodes** 2018-11-14 01:17 UTC

**Comment by nrichards** [comment] 2018-11-14 01:42
Works for me, now after updating the Chrome extension to 0.3.7 :)

**Comment by jeff9315** [comment] 2018-11-14 10:55
Works for me. Thank you SO MUCH kevinwucodes!!

I have to recreate my Quicklinks though. Is that expected? I had previously removed and readded Quicklings though. So maybe that's the reason.
